#ifndef TEST_H
#define TEST_H

#define COMMODITYDEFINITION 301
#define CLASSDEFINITION 302
#define SERIESDEFINITIONBASE 303
#define SERIESDEFINITIONEXTENDED 304
#define COMBINATIONDEFINITION 305

#define ADDORDER 330
#define MODIFYORDER 331
#define DELETEORDER 332
#define TRADE 350
#define TRADEAMENDMENT 356

#endif
